name: Simple Workflow

on:
    workflow_dispatch:
        inputs:
            city:
                description: 'Current city'
                required: yes
                default: 'Moscow'

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 ADD INPUT VARIABLE TO ARTIFACT
          run: |
            echo "My city is: ${{ github.event.inputs.city }}" >> /home/runner/work/devops-school/devops-school/log.txt
        - name: 1.4 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.txt
              path: /home/runner/work/devops-school/devops-school/log.txt
